### ISSUE TITLE
How do you plot the MobileNet-V3,EfficientNet,etc inFigure4

### ISSUE THREAD

**Issue by Liuyang829** [blackfeather-wang/GFNet-Pytorch#1]
Thanks for your great work which inspires me a lot.
I understand the process of budgeted batch classification, you set a threshold to every classifier, so you can calcuate the FLOPs via different stages with a rate. But in the baseline in figure4 just like MobileNet-V3,EfficientNet, how do you get the result of multi flops with different accuracy. You esemble them with early-exit? or other settings? Thank you.

**Comment by Liuyang829** [comment]
Sorry, I see the details in appendix A.3.Thank you.

**Comment by blackfeather-wang** [comment]
Thank you for your attention to our work!
The baseline results in Figure4 of the paper are individual points of models with various sizes (associated with input resolutions for EfficientNets, MobileNets and MnasNets). We do so since it is shown in MSDNet [1] that ensembling multiple models with early-exit results in inferior performance compared with the original ones. 

[1] Gao Huang, Danlu Chen, Tianhong Li, Felix Wu, Laurens van der Maaten, and Kilian Q Weinberger. Multi-scale dense networks for resource efﬁcient image classiﬁcation. In ICLR, 2018.
